### ISSUE TITLE
isnt working 

### ISSUE THREAD

**Issue by niels377** [Donrskbb/FiveM_Actions_To_Discord#1]
i made a discord webhook en is gives logs of normal chat. but the other logs arent working.

**Comment by Donrskbb** [comment]
Hi @niels377 what framework are you running?

**Comment by niels377** [comment]
esx es esxtended im new to making a server.

**Comment by niels377** [comment]
Ik zie nu dat je ook uit Nederland komt. Wat is je discord dat kunnen we daar verder praten als je me wilt helpen. @Donrskbb

**Comment by Donrskbb** [comment]
> Ik zie nu dat je ook uit Nederland komt. Wat is je discord dat kunnen we daar verder praten als je me wilt helpen. @Donrskbb 

@niels377 
Add me maar op Discord '! Donrskbb.exe#0007'

**Comment by niels377** [comment]
je discord naam werkt niet bij mij mijn discord tag is niels377#8107
